// <auto-generated />
namespace CodeFirstEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class KategoriDetayiToKategoriDetayInKategorisTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KategoriDetayiToKategoriDetayInKategorisTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202003090646204_KategoriDetayiToKategoriDetayInKategorisTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
